# Example setup for Kinect cameras
kinect_camera:
  ros__parameters:
    auto_exposure: false
    auto_white_balance: false
    color_depth_synchronization: false
    color_camera_info_url: 'package://chris_ros_turtlebot2/param/kinect_camera_info.yaml'
    color_frame_id: 'camera_rgb_optical_frame'
    color_topic_name: 'image_raw'
    color_mode: 'VGA_30Hz'
    color_time_offset: -0.033
    data_skip: 0
    depth_camera_info_url: 'package://chris_ros_turtlebot2/param/kinect_camera_info.yaml'
    depth_frame_id: 'camera_depth_optical_frame'
    depth_ir_offset_x: 5.0
    depth_ir_offset_y: 4.0
    depth_mode: 'VGA_30Hz'
    depth_registration: true
    depth_time_offset: -0.033
    depth_topic_name: "depth/image"
    device_id: '' # Use any device (assuming only one on bus)
    enable_reconnect: true
    exposure: 0
    ir_frame_id: 'camera_ir_optical_frame'
    ir_mode: 'VGA_30Hz'
    ir_time_offset: -0.033
    ir_topic_name: "ir/image"
    use_color: false
    use_depth: true
    use_device_time: false
    use_ir: true
    use_sim_time: false
    z_offset_mm: 0
    z_scaling: 0.0
