scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: shadows
      type: laser_filters/ScanShadowsFilter
      params:
        min_angle:  10.0
        max_angle: 170.0
        neighbors:   3
        window:      1
    filter2:
      name: range
      type: laser_filters/LaserScanRangeFilter
      params:
        lower_threshold: 0.3175
        upper_threshold: 3.980
