/**:
    ros__parameters:
      video_device: "/dev/video0"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "camera_rgb_optical_frame"
      pixel_format: "yuyv"
      image_width: 640
      image_height: 480
      camera_name: "astra_camera"
      camera_info_url: "package://chris_ros_turtlebot2/param/camera_info.yaml"
